<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE building [
    <!ELEMENT building (room)+>
        <!ELEMENT room (created,desks)+>
            <!ATTLIST room id ID #REQUIRED>
            <!ELEMENT created (date)>
                <!ELEMENT date (#PCDATA)>
            <!ELEMENT desks (desknum)>
                <!ELEMENT desknum (#PCDATA)>
]>
<building>
    <room id="r1">
        <created>
            <date>2010/10/11</date>
        </created>
        <desks>
            <desknum>2</desknum>
        </desks>
    </room>
    <room id="r2">
        <created>
            <date>2010/10/12</date>
        </created>
        <desks>
            <desknum>1</desknum>
        </desks>
    </room>
    <room id="r3">
        <created>
            <date>2010/10/13</date>
        </created>
        <desks>
            <desknum>0</desknum>
        </desks>
    </room>
    
</building>